# Generated by Django 2.1.5 on 2019-02-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_editors_pick',
            field=models.BooleanField(default=False),
        ),
    ]
