# Generated by Django 2.1.5 on 2019-02-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190219_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='monitor.jpg', upload_to='blog_pics/'),
        ),
    ]
