# Generated by Django 2.1.5 on 2019-02-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190219_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Travel', 'Travel'), ('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Lifestyle', 'Lifestyle'), ('Fashion', 'Fashion')], default='Science', max_length=80),
        ),
    ]
